- name: Installataion of Lampstack (Ubuntu)
  apt:
    name:
      - apache2
      - libapache2-mod-php
      - mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Installataion of Lampstack (Ubuntu)
  dnf:
    name:
      - httpd
      - php
      - mariadb-server
    state: latest
  when: ansible_distribution == "CentOS"

